[theme]
base = "light"
primaryColor = "#155eef"
backgroundColor = "#f3f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#172033"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
